name: cicd

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: Set up JDK 17 
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'zulu'

    - name: Setup .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'
    
    - name: Restore Dependencies
      run: dotnet restore ./Vladify

    - name: Install SonarCloud scanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Start Analysis
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: 
        dotnet sonarscanner begin
        /k:"Vainn2332_Vladify"
        /o:"vainn2332"
        /d:sonar.token="$SONAR_TOKEN"
        /d:sonar.host.url="https://sonarcloud.io"
        /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml"

    - name: Build
      run: dotnet build ./Vladify --no-restore --configuration Release
    
    - name: Running Tests
      run: dotnet test ./Vladify --no-build --configuration Release --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        
    - name: End Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
      
  